#!/bin/bash

# Copyright 2013 Rene Hartmann
# 
# This file is part of git-lock.
# 
# git-lock is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# git-lock is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with git-lock.  If not, see <http://www.gnu.org/licenses/>.
# 
# Additional permission under GNU GPL version 3 section 7:
# 
# If you modify the Program, or any covered work, by linking or
# combining it with the OpenSSL project's OpenSSL library (or a
# modified version of that library), containing parts covered by the
# terms of the OpenSSL or SSLeay licenses, the licensors of the Program
# grant you additional permission to convey the resulting work.
# Corresponding Source for a non-source form of such a combination
# shall include the source code for the parts of OpenSSL used as well
# as that of the covered work.

# git-lock script which will delegate all commands to lock-client-lib.sh

LOG_LEVEL_QUIET=0
LOG_LEVEL_ERROR=1
LOG_LEVEL_INFO=2
LOG_LEVEL_DEBUG=3
logLevel=$LOG_LEVEL_INFO

# Check if a log level was given
param="${1:-}"
if [ -n "$param" ]; then
	case "$param" in
		--quiet) logLevel=$LOG_LEVEL_QUIET; shift;;
		--error) logLevel=$LOG_LEVEL_ERROR; shift;;
		--info) logLevel=$LOG_LEVEL_INFO; shift;;
		--debug) logLevel=$LOG_LEVEL_DEBUG; shift;;
	esac
fi

# Get the log device, so that we can redirect logging message directly to the tty device
# We can't use tty to get the log device, because tty is not available everywhere e.g. in MinGW
ttyDevice=$(perl -e 'use POSIX qw(ttyname); print POSIX::ttyname(2);')

# Function to log messages to the proper output device
logMessage() {
	if [ -n "$ttyDevice" ]; then
		echo "$1" > "$ttyDevice"
	else
		echo "$1" >> "git-lock.log"
	fi
}

# Function to ask the user for input
askForInput() {
	checkParameter 1 "askForInput() [QUESTION]" "$@"
	question="$1"
	
	read -p "$question" answer
	echo "$answer"
}

# Import the lock-client functions
. "${LOCK_CLIENT_BIN_DIR}"lock-client-lib.sh

returnValue=$(lockClient "$@")
returnCode=$?
if [ -n "$returnValue" ]; then
	logInfo "$returnValue"
fi
exit $returnCode